# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Fast Mapping

on:
  workflow_call:
    # workaround until unified workflow is implemented
    inputs:
      component-name:
        default: fast-mapping
        required: false
        type: string

permissions:
  contents: read

defaults:
  run:
    working-directory: src/components/fast-mapping

jobs:
  lint:
    name: '[${{ inputs.component-name }}] Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          sparse-checkout: ./src/components/fast-mapping
          persist-credentials: false

      - name: Lint
        shell: bash
        run: |
          make lint

  license-check:
    name: '[${{ inputs.component-name }}] License Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          sparse-checkout: src/components/fast-mapping
          persist-credentials: false

      - name: Run REUSE
        shell: bash
        run: |
          make license-check

  build-test:
    needs: [lint, license-check]
    name: '[${{ inputs.component-name }}] Build & Test (${{ matrix.ros_distro }})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          sparse-checkout: src/components/fast-mapping
          persist-credentials: false

      - name: Build [colcon]
        shell: bash
        run: |
          ROS_DISTRO=${{ matrix.ros_distro }} make build

      - name: Run Tests
        shell: bash
        run: |
          ROS_DISTRO=${{ matrix.ros_distro }} make test

      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: 'test-results-fast-mapping-${{ matrix.ros_distro }}'
          if-no-files-found: error
          path: |
            **/build/fast_mapping/Testing
            **/build/fast_mapping/test_results

  build-package:
    needs: [build-test]
    name: '[${{ inputs.component-name }}] Build Package (${{ matrix.ros_distro }})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          sparse-checkout: src/components/fast-mapping
          persist-credentials: false

      - name: Build package
        shell: bash
        run: |
          ROS_DISTRO=${{ matrix.ros_distro }} make package

      - name: Collect build artifacts
        shell: bash
        run: |
          mkdir -p output/fast-mapping
          find . -name "*.deb" -not -name "*-build-deps_*" -not -name "*-dbgsym_*" -exec mv {} output/fast-mapping \; 2>/dev/null
          if [ "$(ls -1 output/fast-mapping | wc -l)" -gt 0 ]; then
            echo "Debian packages collected.";
          else
            echo "No Debian packages found!";
            exit 1;
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: packages-fast-mapping-${{ matrix.ros_distro }}
          if-no-files-found: error
          path: |
            **/output/fast-mapping/*.deb
