# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Collaborative SLAM

on:
  workflow_call:
    inputs:
      # workaround until unified workflow is implemented
      component-name:
        default: collaborative-slam
        required: false
        type: string

permissions:
  contents: read

defaults:
  run:
    working-directory: src/components/collaborative-slam

jobs:
  license-check:
    name: '[${{ inputs.component-name }}] License Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          sparse-checkout: src/components/collaborative-slam
          persist-credentials: false

      - name: Run REUSE
        shell: bash
        run: |
          make license-check
